### ISSUE TITLE
Android-only offline prediction issue in iNaturalistReactNative

### ISSUE THREAD

**Issue by joergmlpts** [inaturalist/vision-camera-plugin-inatvision#10]
iNaturalistReactNative [issue 1038](https://github.com/inaturalist/iNaturalistReactNative/issues/1038) appears to be due to interface discrepancies between the Andoid version and the iOS version which is working fine:

- iNaturalistReactNative passes the URI of a local image file - an absolute path prefixed with `file://` - as parameter `uri`. This works for the iOS version. But this parameter `uri` is passed to [`BitmapFactory.decodeFile`](https://developer.android.com/reference/android/graphics/BitmapFactory#decodeFile(java.lang.String)) which expects a file path and returns `null` since it cannot open the file. This is the [code line in question](https://github.com/inaturalist/vision-camera-plugin-inatvision/blob/144b33c5b9ac7f6b0aa96d910a2dccd8fd6f5364/android/src/main/java/com/visioncameraplugininatvision/VisionCameraPluginInatVisionModule.java#L107).
- The `null` result is passed to `getWidth()` which is mentioned in this iNaturalistReactNative issue.
- iNaturalistReactNative expects an array of predictions as return value. But the predictions are returned as an object of a single name-value pair with name `predictions` and this array as its value. (A [comment](https://github.com/inaturalist/vision-camera-plugin-inatvision/blob/144b33c5b9ac7f6b0aa96d910a2dccd8fd6f5364/android/src/main/java/com/visioncameraplugininatvision/VisionCameraPluginInatVisionModule.java#L132) states that the URI is also returned but this is not the case.)

Would it be possible to change the interface to match what iOS does and iNaturalistReactNative expects, that is to accept a URI and return an array of predictions?

**Comment by jtklein** [comment]
Thank you @joergmlpts, I have merged the changes related to the URI.
We are using the same plugin in Seek, and for legacy reasons there the structure of the expected return differs between Android and iOS. I have reverted the changes you made towards changing the Android return object.

I will make a PR in iNatRN to see if this fixes the original issue there.

**Comment by joergmlpts** [comment]
Thanks for looking into this, @jtklein.

iNatRN will still crash due to the different return object. I fixed the URI issue first and then encountered another crash due to the return type.

We could check the returned value's type in iNatRN and extract the array from the object when needed. Maybe @kueda rather wants a new branch in `vision-camera-plugin-inatvision` that implements the same interface for Android and iOS.

**Comment by joergmlpts** [comment]
A change for iNatRN to accept both return types [has been developed](https://github.com/inaturalist/iNaturalistReactNative/compare/main...joergmlpts:iNaturalistReactNative:1038-offline-suggestions-dont-work-in-android) and tested on Android.

**Comment by jtklein** [comment]
Thanks,
I have opened a PR to incorporate those changes here as well: https://github.com/inaturalist/iNaturalistReactNative/pull/1110

I also have opened up another issue here for the changes to consolidate the return types of the frame processor plugin and prediction from file function on Android and iOS here: https://github.com/inaturalist/vision-camera-plugin-inatvision/issues/13

**Comment by jtklein** [comment]
This is fixed I believe. The change has bee merged into iNatRN already.
